[tools]
go = "1.26.2"
golangci-lint = "2.11.4"
"go:golang.org/x/tools/cmd/goimports" = "0.31.0"

[tasks.all]
description = "Run imports, fmt, and lint"
run = [
  "mise run imports",
  "mise run fmt",
  "mise run lint",
]

[tasks.imports]
description = "Format Go imports"
run = "find . -name '*.go' | xargs goimports -w"

[tasks.fmt]
description = "Format Go files"
run = "go fmt ./..."

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run ./..."
